export enum TRANSACTION_TYPES {
  WALLET_TO_BALANCE = 'WALLET_TO_BALANCE',
  BALANCE_TO_WALLET = 'BALANCE_TO_WALLET',
  BALANCE_TO_BANK = 'BALANCE_TO_BANK',
  BANK_TO_BALANCE = 'BANK_TO_BALANCE',
}
export enum TRANSACTION_STATUS {
  DONE = 'DONE',
  PENDING = 'PENDING',
  DECLINED = 'DECLINED',
  CANCELED = 'CANCELED',
}
